package rei.calculator;

import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shakeel Ahmed
 */
public class AssumptionPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public AssumptionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        annual_expense_app = new javax.swing.JTextField();
        annual_rate_app = new javax.swing.JTextField();
        annual_property_app = new javax.swing.JTextField();
        selling_cost = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(246, 245, 245));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        setPreferredSize(new java.awt.Dimension(934, 524));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel1.setText("Assumptions Credentials");

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel2.setText("Annual Rate Appreciation (%)");

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel3.setText("Annual Expense Appreciation (%)");

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel4.setText("Annual Property Appreciation (%)");

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel6.setText("Selling Costs (%)");

        annual_expense_app.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        annual_expense_app.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGained_perc(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focusLost_perc(evt);
            }
        });
        annual_expense_app.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validateKey(evt);
            }
        });

        annual_rate_app.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        annual_rate_app.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGained_perc(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focusLost_perc(evt);
            }
        });
        annual_rate_app.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validateKey(evt);
            }
        });

        annual_property_app.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        annual_property_app.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGained_perc(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focusLost_perc(evt);
            }
        });
        annual_property_app.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validateKey(evt);
            }
        });

        selling_cost.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        selling_cost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGained_perc(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focusLost_perc(evt);
            }
        });
        selling_cost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validateKey(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(225, 227, 228));
        jLabel5.setForeground(new java.awt.Color(196, 199, 200));
        jLabel5.setText("________________________________________________________________________________________________________________________________");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(annual_property_app, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(selling_cost, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(annual_rate_app, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(annual_expense_app)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annual_rate_app, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annual_expense_app, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annual_property_app, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selling_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(216, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void focusGained_perc(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGained_perc
        // TODO add your handling code here:
        JTextField source = (JTextField) evt.getSource();
        if(!source.getText().equalsIgnoreCase("")){
            source.setText(Format.formatTo2Float(Float.valueOf(source.getText().replace("%",""))));
        }
    }//GEN-LAST:event_focusGained_perc

    private void focusLost_perc(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLost_perc
        // TODO add your handling code here:
        JTextField source = (JTextField) evt.getSource();
        if(!source.getText().equalsIgnoreCase("")){
            source.setText(Format.formatToPercent(source.getText()));
        }
    }//GEN-LAST:event_focusLost_perc

    private void validateKey(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validateKey
        // TODO add your handling code here:
        JTextField source = (JTextField) evt.getSource();
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || evt.getKeyCode() == 8 ||  evt.getKeyChar() == '.' || (evt.getKeyCode() >=37 && evt.getKeyCode() <=40)) {
            source.setEditable(true);
        } else {
            source.setEditable(false);
        }
    }//GEN-LAST:event_validateKey

    private float getTFValue_Perc(JTextField src){
        if(!src.getText().equalsIgnoreCase(""))
            return Format.parse_perc(src.getText());
        else return 0.00f;
    }    
        
    public float getAnnualExpenseApp() {
        return this.getTFValue_Perc(annual_expense_app);
    }

    public float getAnnualPropertyAapp() {
        return this.getTFValue_Perc(annual_property_app);
    }

    public float getAnnualRateApp() {
        return this.getTFValue_Perc(annual_rate_app);
    }

    public float getSellingCost() {
        return this.getTFValue_Perc(selling_cost);
    }


    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField annual_expense_app;
    private javax.swing.JTextField annual_property_app;
    private javax.swing.JTextField annual_rate_app;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField selling_cost;
    // End of variables declaration//GEN-END:variables
}
