package rei.calculator;

import java.util.Formatter;
import javax.swing.JTextField;
import static rei.calculator.Format.fmt;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shakeel Ahmed
 */
public class ExpensePanel extends javax.swing.JPanel {

    private static final float RATE = 1200.00f;
    /**
     * Creates new form NewJPanel
     */
    public ExpensePanel() {
        initComponents();
        System.out.println("here after");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        total_fixed_expense = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        electric = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        water_and_sewer = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pmi = new javax.swing.JTextField();
        garbage = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        hoa = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        monthly_taxes = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        insurance = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        miscellaneous = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        cap_ex_perc = new javax.swing.JTextField();
        cap_ex_dollar = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        management_fee_dollar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        repair_maint_perc = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        repair_maint_dollar = new javax.swing.JTextField();
        total_variable_expense = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        vacancy_perc = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        vacancy_dollar = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        management_free_perc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(246, 245, 245));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        setPreferredSize(new java.awt.Dimension(934, 524));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel1.setText("Expenditure Information");

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel2.setText("Total Fixed Expense");

        total_fixed_expense.setEditable(false);
        total_fixed_expense.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        total_fixed_expense.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                total_fixed_expenseFocusLost(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel14.setText("Fixed Expenses (USD)");

        jLabel15.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel15.setText("Variable Expeses (USD)");

        electric.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        electric.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                updateTFE(evt);
            }
        });
        electric.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ExpensePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ExpensePanel.this.focusLost(evt);
            }
        });
        electric.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                electricCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        electric.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validateKey(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel17.setText("Electric");

        water_and_sewer.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        water_and_sewer.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                updateTFE(evt);
            }
        });
        water_and_sewer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ExpensePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ExpensePanel.this.focusLost(evt);
            }
        });
        water_and_sewer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validateKey(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel19.setText("Water and Sewer");

        jLabel20.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel20.setText("PMI");

        pmi.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        pmi.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                updateTFE(evt);
            }
        });
        pmi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ExpensePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ExpensePanel.this.focusLost(evt);
            }
        });
        pmi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validateKey(evt);
            }
        });

        garbage.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        garbage.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                updateTFE(evt);
            }
        });
        garbage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ExpensePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ExpensePanel.this.focusLost(evt);
            }
        });
        garbage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validateKey(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel23.setText("Garbase");

        jLabel25.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel25.setText("HOA ");

        hoa.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        hoa.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                updateTFE(evt);
            }
        });
        hoa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ExpensePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ExpensePanel.this.focusLost(evt);
            }
        });
        hoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validateKey(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel26.setText("Monthly Taxes");

        monthly_taxes.setEditable(false);
        monthly_taxes.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel29.setText("Insurance");

        insurance.setEditable(false);
        insurance.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel30.setText("Miscellaneous");

        miscellaneous.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        miscellaneous.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                updateTFE(evt);
            }
        });
        miscellaneous.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ExpensePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ExpensePanel.this.focusLost(evt);
            }
        });
        miscellaneous.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validateKey(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel32.setText("Repairs/Maint ($)");

        jLabel33.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel33.setText("Cap. Ex. (%)");

        cap_ex_perc.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        cap_ex_perc.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                updateTVE(evt);
            }
        });
        cap_ex_perc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGained_Parc(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focusLost_Perc(evt);
            }
        });
        cap_ex_perc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validateKey(evt);
            }
        });

        cap_ex_dollar.setEditable(false);
        cap_ex_dollar.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N

        jLabel34.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel34.setText("Cap. Ex. ($)");

        jLabel35.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel35.setText("Management Fee ($)");

        management_fee_dollar.setEditable(false);
        management_fee_dollar.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel3.setText("Total Variable Expense");

        repair_maint_perc.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        repair_maint_perc.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                updateTVE(evt);
            }
        });
        repair_maint_perc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGained_Parc(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focusLost_Perc(evt);
            }
        });
        repair_maint_perc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validateKey(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel36.setText("Repairs/Maint (%)");

        repair_maint_dollar.setEditable(false);
        repair_maint_dollar.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N

        total_variable_expense.setEditable(false);
        total_variable_expense.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N

        jLabel37.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel37.setText("Vacancy (%)");

        vacancy_perc.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        vacancy_perc.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                updateTVE(evt);
            }
        });
        vacancy_perc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGained_Parc(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focusLost_Perc(evt);
            }
        });
        vacancy_perc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validateKey(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel38.setText("Vacancy ($)");

        vacancy_dollar.setEditable(false);
        vacancy_dollar.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N

        jLabel39.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel39.setText("Management Fee (%)");

        management_free_perc.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        management_free_perc.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                updateTVE(evt);
            }
        });
        management_free_perc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGained_Parc(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focusLost_Perc(evt);
            }
        });
        management_free_perc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validateKey(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(225, 227, 228));
        jLabel16.setForeground(new java.awt.Color(196, 199, 200));
        jLabel16.setText("________________________________________________________________________________________________________________________________");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(electric, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(water_and_sewer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pmi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(garbage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthly_taxes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insurance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(miscellaneous, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total_fixed_expense, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(repair_maint_perc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(repair_maint_dollar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cap_ex_perc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cap_ex_dollar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vacancy_perc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vacancy_dollar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(management_free_perc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(management_fee_dollar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_variable_expense, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel15)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(total_variable_expense, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(repair_maint_perc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(repair_maint_dollar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cap_ex_perc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cap_ex_dollar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vacancy_perc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vacancy_dollar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(management_free_perc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(management_fee_dollar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(total_fixed_expense, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(electric, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(water_and_sewer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pmi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(garbage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthly_taxes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insurance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(miscellaneous, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private static float getTFValue_Dollar(JTextField src){
        if(!src.getText().equalsIgnoreCase(""))
            return Format.parse(src.getText());
        else return 0.00f;
    }    
    
    private static float getTFValue_Perc(JTextField src){
        if(!src.getText().equalsIgnoreCase(""))
            return Format.parse_perc(src.getText());
        else return 0.00f;
    }    
    
    private void updateTVE(){
        float rep_and_main = getTFValue_Dollar(this.repair_maint_dollar);
        float cap = getTFValue_Dollar(this.cap_ex_dollar);
        float vacancy = getTFValue_Dollar(this.vacancy_dollar);
        float manag = getTFValue_Dollar(this.management_fee_dollar);
        float[] values = REI_Calculations.variable_expenses_monthly(vacancy, rep_and_main, cap, manag);
        this.total_variable_expense.setText(Format.formatToCurrency(String.valueOf(values[0])));
    }
    
    private void updateTFE(){
        float electric = getTFValue_Dollar(this.electric);
        float w_and_s = getTFValue_Dollar(this.water_and_sewer);
        float pmi = getTFValue_Dollar(this.pmi);
        float garbage = getTFValue_Dollar(this.garbage);
        float hoa = getTFValue_Dollar(this.hoa);
        float monthly_taxes = getTFValue_Dollar(this.monthly_taxes);
        float insurance = getTFValue_Dollar(this.insurance);
        float misc = getTFValue_Dollar(this.miscellaneous);
        float[] values = REI_Calculations.fixed_expenses_monthly(electric, w_and_s, pmi, garbage, hoa, insurance, monthly_taxes, misc);
        this.total_fixed_expense.setText(Format.formatToCurrency(Format.formatTo2Float(values[0])));
//        System.out.println("e"+electric);
//        System.out.println("w"+w_and_s);
//        System.out.println("pmi"+pmi);
//        System.out.println("g"+garbage);
//        System.out.println("h"+hoa);
//        System.out.println("mt"+monthly_taxes);
//        System.out.println("i"+insurance);
//        System.out.println("misc"+misc);
//        System.out.println("t"+values[0]);
    }
    
    private void focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGained
        // TODO add your handling code here:
        JTextField source = (JTextField) evt.getSource();
        if(!source.getText().equalsIgnoreCase("")){
            source.setText(Format.formatTo2Float(Format.parse(source.getText())));
        }
    }//GEN-LAST:event_focusGained

    private void focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLost
        // TODO add your handling code here:
        JTextField source = (JTextField) evt.getSource();
        if(!source.getText().equalsIgnoreCase("")){
            source.setText(Format.formatToCurrency(source.getText()));
        }
    }//GEN-LAST:event_focusLost

    private void total_fixed_expenseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_total_fixed_expenseFocusLost
//        this.updateTFE(192900.00f);
        // TODO add your handling code here:
    }//GEN-LAST:event_total_fixed_expenseFocusLost

    private void updateTFE(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_updateTFE
        // TODO add your handling code here:
        this.updateTFE();
    }//GEN-LAST:event_updateTFE

    private void validateKey(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validateKey
        // TODO add your handling code here:
        JTextField source = (JTextField) evt.getSource();
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || evt.getKeyChar() == '.' || evt.isControlDown() || evt.getKeyCode() == 8 || evt.getKeyCode() == 16 || evt.getKeyCode() == 17 ||  (evt.getKeyCode() >=37 && evt.getKeyCode() <=40)) {
            if(evt.getKeyChar() == '.'  && source.getText().contains("."))
                source.setEditable(false);
            else source.setEditable(true);
        } else source.setEditable(false);
    }//GEN-LAST:event_validateKey

    private void focusLost_Perc(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLost_Perc
        // TODO add your handling code here:
        JTextField source = (JTextField) evt.getSource();
        if(!source.getText().equalsIgnoreCase("")){
            source.setText(Format.formatToPercent(source.getText()));
        }
    }//GEN-LAST:event_focusLost_Perc

    private void focusGained_Parc(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGained_Parc
        // TODO add your handling code here:
        JTextField source = (JTextField) evt.getSource();
        if(!source.getText().equalsIgnoreCase("")){
            source.setText(Format.formatTo2Float(Float.valueOf(source.getText().replace("%",""))));
        }
    }//GEN-LAST:event_focusGained_Parc

    private void updateTVE(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_updateTVE
        // TODO add your handling code here:
        JTextField source = (JTextField) evt.getSource();
//        if(!source.getText().equalsIgnoreCase("")){
//            System.out.println("Value here: "+Format.parse_perc(source.getText()));
            float total = (this.getTFValue_Perc(source) * this.RATE)/100;
            if(evt.getSource().hashCode() == this.repair_maint_perc.hashCode())
                this.repair_maint_dollar.setText(total+"");
            else if(evt.getSource().hashCode() == this.cap_ex_perc.hashCode())
                this.cap_ex_dollar.setText(total+"");
            else if(evt.getSource().hashCode() == this.vacancy_perc.hashCode())
                this.vacancy_dollar.setText(total+"");
            else this.management_fee_dollar.setText(total+"");
            this.updateTVE();
//        }
    }//GEN-LAST:event_updateTVE

    private void electricCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_electricCaretPositionChanged
        // TODO add your handling code here:
//        this.updateTFE(0.00f);
    }//GEN-LAST:event_electricCaretPositionChanged

    public static float getRATE() {
        return RATE;
    }

    public static float getCapExValue() {
        return getTFValue_Dollar(cap_ex_dollar);
    }

    public static float getCapExPerc() {
        return getTFValue_Dollar(cap_ex_perc);
    }

    public static float getElectric() {
        return getTFValue_Dollar(electric);
    }

    public static float getGarbage() {
        return getTFValue_Dollar(garbage);
    }

    public static float getHoa() {
        return getTFValue_Dollar(hoa);
    }

    public static float getInsurance() {
        return getTFValue_Dollar(insurance);
    }

    public static float getManagementFeeValue() {
        return getTFValue_Dollar(management_fee_dollar);
    }

    public static float getManagementFreePerc() {
        return getTFValue_Perc(management_free_perc);
    }

    public static float getMiscellaneous() {
        return getTFValue_Dollar(miscellaneous);
    }

    public static float getMonthlyTaxes() {
        return getTFValue_Dollar(monthly_taxes);
    }

    public static float getPMI() {
        return getTFValue_Dollar(pmi);
    }

    public static float getRepairMaintValue() {
        return getTFValue_Dollar(repair_maint_dollar);
    }

    public static float getRepairMaintPerc() {
        return getTFValue_Dollar(repair_maint_perc);
    }

    public static float getTotalFixedExpense() {
        return getTFValue_Dollar(total_fixed_expense);
    }

    public static float getTotalVariableExpense() {
        return getTFValue_Dollar(total_variable_expense);
    }

    public static float getVacancyValue() {
        return getTFValue_Dollar(vacancy_dollar);
    }

    public static float getVacancyPerc() {
        return getTFValue_Perc(vacancy_perc);
    }

    public static float getWaterAndSewer() {
        return getTFValue_Dollar(water_and_sewer);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField cap_ex_dollar;
    private static javax.swing.JTextField cap_ex_perc;
    private static javax.swing.JTextField electric;
    private static javax.swing.JTextField garbage;
    private static javax.swing.JTextField hoa;
    private static javax.swing.JTextField insurance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private static javax.swing.JTextField management_fee_dollar;
    private static javax.swing.JTextField management_free_perc;
    private static javax.swing.JTextField miscellaneous;
    private static javax.swing.JTextField monthly_taxes;
    private static javax.swing.JTextField pmi;
    private static javax.swing.JTextField repair_maint_dollar;
    private static javax.swing.JTextField repair_maint_perc;
    private static javax.swing.JTextField total_fixed_expense;
    private static javax.swing.JTextField total_variable_expense;
    private static javax.swing.JTextField vacancy_dollar;
    private static javax.swing.JTextField vacancy_perc;
    private static javax.swing.JTextField water_and_sewer;
    // End of variables declaration//GEN-END:variables
}
