package rei.calculator;

import java.text.ParseException;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shakeel Ahmed
 */
public class IncomePanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public IncomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        total_monthly_income_units = new javax.swing.JTextField();
        average_rent_per_unit = new javax.swing.JTextField();
        other_income = new javax.swing.JTextField();
        total_monthly_income = new javax.swing.JTextField();
        number_of_units = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(246, 245, 245));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        setPreferredSize(new java.awt.Dimension(934, 524));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel1.setText("Income Information");

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel2.setText("Number of Units ");

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel3.setText("Average Rent per Unit ($)");

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel4.setText("Total Monthly Rent Income ($)");

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel5.setText("Other Monthly Income ($)");

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel6.setText("Total Monthly Income ($)");

        total_monthly_income_units.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        total_monthly_income_units.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IncomePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IncomePanel.this.focusLost(evt);
            }
        });
        total_monthly_income_units.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validateKey(evt);
            }
        });

        average_rent_per_unit.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        average_rent_per_unit.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                average_rent_per_unitCaretUpdate(evt);
            }
        });
        average_rent_per_unit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IncomePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IncomePanel.this.focusLost(evt);
            }
        });
        average_rent_per_unit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validateKey(evt);
            }
        });

        other_income.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        other_income.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                other_incomeCaretUpdate(evt);
            }
        });
        other_income.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IncomePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IncomePanel.this.focusLost(evt);
            }
        });
        other_income.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validateKey(evt);
            }
        });

        total_monthly_income.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        total_monthly_income.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IncomePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IncomePanel.this.focusLost(evt);
            }
        });
        total_monthly_income.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validateKey(evt);
            }
        });

        number_of_units.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        number_of_units.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        number_of_units.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                number_of_unitsStateChanged(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(225, 227, 228));
        jLabel16.setForeground(new java.awt.Color(196, 199, 200));
        jLabel16.setText("________________________________________________________________________________________________________________________________");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(other_income, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(total_monthly_income, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(average_rent_per_unit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(total_monthly_income_units)
                            .addComponent(number_of_units, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(326, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number_of_units, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(average_rent_per_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(total_monthly_income_units, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(other_income, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(total_monthly_income, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGained
        // TODO add your handling code here:
        JTextField source = (JTextField) evt.getSource();
        if(!source.getText().equalsIgnoreCase("")){
            source.setText(Format.formatTo2Float(Format.parse(source.getText())));
        }
    }//GEN-LAST:event_focusGained

    private void focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLost
        // TODO add your handling code here:
        JTextField source = (JTextField) evt.getSource();
        if(!source.getText().equalsIgnoreCase("")){
            source.setText(Format.formatToCurrency(source.getText()));
        }

    }//GEN-LAST:event_focusLost

    private void validateKey(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validateKey
        // TODO add your handling code here:
        JTextField source = (JTextField) evt.getSource();
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || evt.getKeyCode() == 8 || evt.getKeyChar() == '.' || evt.getKeyCode() == 16 || evt.getKeyCode() == 17 || (evt.getKeyCode() >=37 && evt.getKeyCode() <=40)) {
            if(evt.getKeyChar() == '.' && source.getText().contains("."))
                source.setEditable(false);
            else source.setEditable(true);
        } else source.setEditable(false);
    }//GEN-LAST:event_validateKey

    private static float getTFValue_Dollar(JTextField src){
        if(!src.getText().equalsIgnoreCase(""))
            return Format.parse(src.getText());
        else return 0.00f;
    }    
    private void updateTotalMonthlyRentIncome(){
        this.total_monthly_income_units.setText(Format.format((int) this.number_of_units.getValue() * this.getTFValue_Dollar(this.average_rent_per_unit)));
    }
    
    private void updateTotalMonthlyIncome(){
        this.total_monthly_income.setText(Format.format(this.getTFValue_Dollar(this.total_monthly_income_units)+this.getTFValue_Dollar(this.other_income)));
    }
    
    private void number_of_unitsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_number_of_unitsStateChanged
        // TODO add your handling code here:
        this.updateTotalMonthlyRentIncome();
//        this.setTotalMonthlyIncome();
    }//GEN-LAST:event_number_of_unitsStateChanged

    private void average_rent_per_unitCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_average_rent_per_unitCaretUpdate
        // TODO add your handling code here:
        this.updateTotalMonthlyRentIncome();
        this.updateTotalMonthlyIncome();
    }//GEN-LAST:event_average_rent_per_unitCaretUpdate

    private void other_incomeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_other_incomeCaretUpdate
        // TODO add your handling code here:
        this.updateTotalMonthlyIncome();
    }//GEN-LAST:event_other_incomeCaretUpdate

    public static float getAverageRentPerUnit() {
        return getTFValue_Dollar(average_rent_per_unit);
    }

    public static int getNumbe_of_units() {
        try{
            number_of_units.commitEdit();
        } catch (ParseException e) { e.getMessage(); }
        return (int) number_of_units.getValue();
    }

    public static float getOtherIncome() {
        return getTFValue_Dollar(other_income);
    }

    public static float getTotalMonthlyIncome() {
        return getTFValue_Dollar(total_monthly_income);
    }

    public static float getTotalMonthlyIncomeUnits() {
        return getTFValue_Dollar(total_monthly_income_units);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField average_rent_per_unit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private static javax.swing.JSpinner number_of_units;
    private static javax.swing.JTextField other_income;
    private static javax.swing.JTextField total_monthly_income;
    private static javax.swing.JTextField total_monthly_income_units;
    // End of variables declaration//GEN-END:variables
}
